shinyUI(fluidPage(
  titlePanel("South African Crime Data"),
  
  sidebarLayout(
    sidebarPanel(
      
      selectInput("province",
                  label = "Select province",
                  choices = list("WC"),
                  selected = "WC"),
      
      selectInput("police",
                  label = "Select police station",
                  choices = list("Albertinia", "Ashton", "Athlone", "Atlantis", 
                                 "Barrydale", "Beaufort West", "Belhar", "Bellville",           
                                 "Bellville South", "Bishop Lavis", "Bonnievale", "Bothasig",            
                                 "Brackenfell",          "Bredasdorp",           "Caledon",              "Calitzdorp",          
                                 "Camps Bay",            "Cape Town Central",    "Ceres",                "Citrusdal",           
                                 "Clanwilliam",          "Claremont",            "Cloetesville",         "Conville",            
                                 "Da Gamaskop",          "Darling",              "De Doorns",            "De Rust",             
                                 "Delft",                "Dieprivier",           "Doring Bay",           "Durbanville",         
                                 "Dysselsdorp",          "Eendekuil",            "Elands Bay",           "Elsies River",        
                                 "Fish Hoek",            "Franschhoek",          "Gans Bay",             "Genadendal",          
                                 "George",               "Goodwood",             "Gordons Bay",          "Graafwater",          
                                 "Grabouw",              "Grassy Park",          "Groot",                "Groot Brakrivier",    
                                 "Gugulethu",            "Harare",               "Heidelberg",           "Hermanus",            
                                 "Hopefield",            "Hout Bay",             "Kensington",           "Khayelitsha",         
                                 "Kirstenhof",           "Klapmuts",             "Klawer",               "Kleinmond",           
                                 "Kleinvlei",            "Knysna",               "Kraaifontein",         "Kuilsrivier",         
                                 "Kwanokuthula",         "Kwanonqaba",           "Laaiplek",             "Ladismith",           
                                 "Laingsburg",           "Lambertsbaai",         "Langa",                "Langebaan",           
                                 "Lansdowne",            "Leeu",                 "Lentegeur",            "Lingelethu",          
                                 "Lutzville",            "Lwandle",              "Macassar",             "Maitland",            
                                 "Malmesbury",           "Manenberg",            "Mbekweni",             "McGregor",            
                                 "Melkbosstrand",        "Mfuleni",              "Milnerton",            "Mitchells Plain",     
                                 "Montagu",              "Moorreesburg",         "Mossel Bay",           "Mowbray",             
                                 "Muizenberg",           "Murraysburg",          "Napier",               "Nuwerus",             
                                 "Nyanga",               "Ocean View",           "Oudtshoorn",           "Paarl",               
                                 "Paarl East",           "Pacaltsdorp",          "Parow",                "Philadelphia",        
                                 "Philippi",             "Philippi East",        "Piketberg",            "Pinelands",           
                                 "Plettenberg Bay",      "Porterville",          "Prince Albert",        "Prince Alfred Hamlet",
                                 "Ravensmead",           "Rawsonville",          "Redelinghuys",         "Riebeeck West",       
                                 "Riversdale",           "Riviersonderend",      "Robertson",            "Rondebosch",          
                                 "Saldanha",             "Saron",                "Sea Point",            "Simon",               
                                 "Somerset West",        "St Helena Bay",        "Stanford",             "Steenberg",           
                                 "Stellenbosch",         "Still Bay",            "Strand",               "Strandfontein",       
                                 "Struisbaai",           "Suurbraak",            "Swellendam",           "Table Bay Harbour",   
                                 "Table View",           "Thembalethu",          "Touws River",          "Tulbagh",             
                                 "Uniondale",            "Vanrhynsdorp",         "Villiersdorp",         "Vredenburg",          
                                 "Vredendal",            "Wellington",           "Wolseley",             "Woodstock",           
                                 "Worcester",            "Wynberg"    ),
                  selected = "Albertinia"),
      
      selectInput("crime",
                  label = "Select crime",
                  choices = list("All theft not mentioned elsewhere",
                                 "Arson",
                                 "Assault with the intent to inflict grievous bodily harm",
                                 "Attempted murder", 
                                 "Burglary at non-residential premises",
                                 "Burglary at residential premises",
                                 "Carjacking",
                                 "Commercial crime",
                                 "Common assualt",
                                 "Common robbery",
                                 "Crimen injuria",
                                 "Culpable homicide", 
                                 "Driving under the influence of alcohol or drugs",
                                 "Drug-related crime",
                                 "Kidnapping",
                                 "Malicious injury to property",
                                 "Murder",
                                 "Neglect and ill-treatment of children",
                                 "Public violence",
                                 "Robbery at non-residential premises",
                                 "Robbery at residential premises",
                                 "Robbery with aggravating circumstances",
                                 "Shoplifting",
                                 "Stock-theft",
                                 "Theft of motor vehicle and motorcycle",
                                 "Theft out of or from motor vehicle",
                                 "Total Sexual Crimes",
                                 "Truck hijacking",
                                 "Unlawful possession of firearms and ammunition"),
                  selected = "Murder")
    ),
    
    mainPanel(plotOutput("graph"))
  )
))